export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Account } from './Account'
export { default as Loading } from './Loading'
export { default as Home } from './Home'
export { default as Catalog } from './Catalog'
export { default as Cart } from './Cart'
export { default as Favourites } from './Favourites'